# Generated by Django 5.1.5 on 2025-01-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0003_alter_usuario_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='categoriaprincipal',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='categoriaprincipal',
            name='propiedad',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='propiedad',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='pago',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='prioridad',
            name='propiedades',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='servicios_extra',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='propiedad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuariologin',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuariologin',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Anfrition',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='CategoriaPrincipal',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Prioridad',
        ),
        migrations.DeleteModel(
            name='ServicioExtra',
        ),
        migrations.DeleteModel(
            name='Propiedad',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='UsuarioLogin',
        ),
    ]
